# Generated by Django 4.1 on 2023-01-16 08:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Name not valid: name must start and ends with letter and can contain only ' ' or '-' special characters ", regex='^[a-zA-Z][a-zA-Z\\-\\s]*$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Name not valid: name must start and ends with letter and can contain only ' ' or '-' special characters ", regex='^[a-zA-Z][a-zA-Z\\-\\s]*$')])),
                ('email', models.EmailField(max_length=256, unique=True, validators=[django.core.validators.EmailValidator(code='Invalid email', message='Please provide valid email address')], verbose_name='email address')),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Password must be between 8-64 characters, can include upper/lower cases, digits and special characters', regex='^.{8,64}$')])),
                ('profile_avatar', models.ImageField(blank=True, null=True, upload_to='users/avatar', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
