# Generated by Django 4.1.7 on 2023-04-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcode',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
