# Generated by Django 4.1.7 on 2023-02-25 13:16

import MusicHub.tracks.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0002_track_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(MusicHub.tracks.models.get_sentinal_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(upload_to=MusicHub.tracks.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'aac'])]),
        ),
    ]
